// <auto-generated />
using System;
using CrudeWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudeWeb.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CrudeWeb.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Autor");

                    b.Property<DateOnly>("DataPublicacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataPublicacao");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Genero");

                    b.Property<string>("NomeLivro")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
